# Site settings
title: CS70
email: admin@eecs70.org
description: > # this means to ignore newlines until "baseurl:"
  Discrete Math and Probability Theory (UC Berkeley).
baseurl: "/su16" # the subpath of your site, e.g. /blog
url: "http://www.eecs70.org" # the base hostname & protocol for your site


# Change this each semester
term_url: "/su16"
term: "Summer 2016"





# Build settings
markdown: kramdown
